apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  namespace: app-nmspc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        image: 141947217581.dkr.ecr.us-east-1.amazonaws.com/application-repo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "db-service.db-nmspc.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "lime"
      imagePullSecrets:
      - name: ecr-registry-key