apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-replicaset
  namespace: db-nmspc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: 141947217581.dkr.ecr.us-east-1.amazonaws.com/sql-database-repo:version1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      imagePullSecrets: 
      - name: ecr-registry-key
      
      
